# Generated by Django 3.1.1 on 2020-10-22 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='block',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('block_code', models.CharField(max_length=100)),
                ('number_of_parking', models.IntegerField(default=1)),
                ('is_block_full', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='parking_lot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_blocks', models.IntegerField()),
                ('is_slot_available', models.BooleanField(default=False)),
                ('address', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ticket_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ticket_vehicle_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_vehicle_name', models.CharField(choices=[('CAR', 'Vé ô tô'), ('MOTOBIKE', 'Vé xe máy'), ('BIKE', 'Vé xe đạp')], max_length=100)),
                ('price', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_img', models.ImageField(upload_to='vehicle/%Y/%m/%d')),
                ('vehicle_img_code', models.ImageField(upload_to='vehicle_code/%Y/%m/%d')),
                ('vehicle_img_text', models.CharField(default='', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(auto_now=True)),
                ('time_out', models.DateTimeField(default='')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LicensePlateAI.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='parking_slot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('block_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LicensePlateAI.block')),
            ],
        ),
        migrations.AddField(
            model_name='block',
            name='parking_lot_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LicensePlateAI.parking_lot'),
        ),
    ]
