# Generated by Django 3.1.1 on 2020-10-23 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlateAI', '0003_ticket_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time_in',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time_out',
            field=models.DateTimeField(blank=True),
        ),
    ]
