# Generated by Django 3.1.1 on 2020-10-23 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlateAI', '0004_auto_20201024_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='time_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
