# Generated by Django 3.1.1 on 2020-10-28 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlateAI', '0005_auto_20201024_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_type_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='LicensePlateAI.ticket_type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='ticket_vehicle_type_id',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='LicensePlateAI.ticket_vehicle_type'),
            preserve_default=False,
        ),
    ]
