# Generated by Django 3.1.1 on 2020-10-28 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlateAI', '0006_auto_20201028_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ticket',
        ),
    ]
