# Generated by Django 3.1.1 on 2020-10-28 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlateAI', '0007_delete_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_in', models.DateTimeField(auto_now_add=True)),
                ('time_out', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('ticket_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LicensePlateAI.ticket_type')),
                ('ticket_vehicle_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LicensePlateAI.ticket_vehicle_type')),
                ('vehicle_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LicensePlateAI.vehicle')),
            ],
        ),
    ]
