# Generated by Django 3.1.1 on 2020-10-28 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LicensePlateAI', '0008_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ticket',
        ),
    ]
